### ISSUE TITLE
Can't install in HACS on current GA version of HA (2021.5.4)

### ISSUE THREAD

**Issue by Lockszmith-GH** [dreed47/redfin#3]
Current version of home assistant is 2021.5.4, HACS integration fails to install with the following message:
> You are running Home Assistant version '2021.5.4', but this repository requires minimum version '2021.6.0' to be installed.

**Comment by dreed47** [comment]
Thats correct.  It relies on HA core 2021.6.0 which obviously hasn't been released yet.   You could run it against the HA dev branch but thats not feasible for most.  I'll add a note to the readme.

**Comment by Lockszmith-GH** [comment]
Thanks for the quick reply!
I'll wait for next month's release.

Like the idea - as history will generate a locally stored graph of the value of the home, and the ability to setup a notification if the value changes substantially.
