### ISSUE TITLE
How to enable?

### ISSUE THREAD

**Issue by Colorado4Wheeler** [dreed47/redfin#6]
I've been hunting around all over the place and cannot see how to configure my home.  The instructions say to install (I did this via HACS) and then use the Integration Component to add and configure a home.  When I try to add an integration, Redfin is not on the list and there is nothing in the instructions that says I need to add a custom sensor manually and, if so, what the parameters should be. 

So, I have it installed, now what?

Per the instructions: "To enable this sensor, add new Redfin integration component in the Home Assistant UI and follow the prompts to add your properties."

Redfin is not on the list of installed integrations nor does it come up when trying to install a new one.

**Comment by dreed47** [comment]
step 1 - install in HACS
step 2 - install in HomeAssistant @ /config/integrations --> Add integration and search for Redfin

**Comment by Colorado4Wheeler** [comment]
Exactly what I assumed was the case, but Redfin doesn't show up.

![image](https://user-images.githubusercontent.com/20329385/121933378-3d2eb800-cd03-11eb-8ef2-6af18c4b69cb.png)

And I figure you might next ask "yea, but did you really install it...?".  I did :).
![image](https://user-images.githubusercontent.com/20329385/121933786-be864a80-cd03-11eb-802c-140fd22a29fd.png)

**Comment by dreed47** [comment]
did you try restarting between step 1 and step 2?

**Comment by Colorado4Wheeler** [comment]
Of course, even if I hadn't known that already, HACS gives you a big red warning about it.

**Comment by dreed47** [comment]
Verify that the redfin folder shows up in your custom_components folder and ensure its got the correct files.  If everything is there then you're having a HomeAssistant issue of some kind.  If the folder is not there or is missing files then it might be a HACS issue.

**Comment by bendiger** [comment]
Having the same issue as well. I've tried rebooting a few times and reinstalling.

**Comment by bendiger** [comment]
I just rolled back to 1.1.3 and it shows up.

**Comment by eric-x-liu** [comment]
Tried rolling back to 1.1.3. It does not work. No error messages

**Comment by dan335** [comment]
hacs.json was missing for me.  After adding it it worked.
